### PR TITLE
Modifications to init and run scripts in preparation for long production run

### PR DESCRIPTION
**Pull request by hdrake**
Once this PR is ready, it can be merged into https://github.com/liuchihl/internal-tide-mixing/pull/1

See individual commits below.

### CODE REVIEW

**Comment by hdrake** [comment]
@liuchihl, can you please also commit the script you used to run the test simulation as well as the one you plan to use to run the full production simulations? It looks like this script only initializes the simulation.

**Comment by hdrake** [comment]
Once this is done, it can be merged into https://github.com/liuchihl/internal-tide-mixing/pull/1

**Comment by liuchihl** [comment]
The run file is here: https://github.com/liuchihl/internal-tide-mixing/blob/3D-realtopo-delta-glw-background-flux-div/run_internal_tide.jl

**Review by liuchihl — APPROVED** [review]
This PR looks great, one thing to add is that the top buoyancy gradient boundary condition should be 0.

**Comment by hdrake** [comment]
@liuchihl, in addition to the changes I've made here, the other thing that should be done is to generalize the initialization script so that we can use *the same initialization script* for all of the simulations we anticipate running in the near future. This means that any changes to variables within the function should be passable by arguments or keyword arguments to the initialization function. We do this for the resolution, slope angle, and tidal velocity, but we may also want to allow other constants to be specified. I think we'll at least want to be able to vary the other relevant timescales: the total run time (or stop time $t_{f}$, the Coriolis parameter $f$, the background buoyancy frequency $N$, and the tidal frequency $\omega_{0}$.

The main problem right now is that many of the diagnostic settings are hard-coded for the frequencies and types of variables we want to save for the short testing runs, but not necessarily the long spin-up or our eventual 10 or 20-day "analysis" period.

I'll leave it up to you how to make these changes. One option is to allow the diagnostic settings to be customized based on Boolean flags and keyword arguments like `slice_avg_frequency`. Another option is to just remove the setting of the diagnostics from the initialization script and to have this be part of the run script.

**Comment by hdrake** [comment]
We also may want to swap out the topography file for a modified file (e.g. where we've smoothed the topography or removed the canyon/sill).

**Pull request merged**
